backend:
  replicaCount: 2
  image:
    repository: ghcr.io/songhai9/anime-review-backend
    tag: "fcd54c6e"
    pullPolicy: IfNotPresent
  service:
    port: 3001
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi
  database:
    host: postgres
    port: "5432"
    name: postgres_db
    user: postgres_user
    secretName: postgres-secrets
    secretKey: POSTGRES_PASSWORD
frontend:
  replicaCount: 1
  image:
    repository: ghcr.io/songhai9/anime-review-frontend
    tag: "fcd54c6e"
    pullPolicy: IfNotPresent
  service:
    port: 3000
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
postgres:
  image:
    repository: postgres
    tag: "16-alpine"
    pullPolicy: IfNotPresent
  database: postgres_db
  user: postgres_user
  service:
    port: 5432
  secretName: postgres-secrets
  secretKey: POSTGRES_PASSWORD
  storage:
    storageClass: gp3
    size: 8Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
ingress:
  enabled: true
  className: nginx
networkPolicies:
  enabled: true
