apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: anime-review
  labels:
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: anilist-frontend
          image: registry.gitlab.com/songhai9/manga-app/frontend:65b74ecb
          resources:
            limits:
              cpu: "200m"
              memory: "128Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
          ports:
            - containerPort: 3000
          env:
            - name: API_URL
              value: http://backend:3001
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
