apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    tier: db
spec:
  ports:
  - port: 3306
    name: db
  clusterIP: None
  selector:
    tier: db

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      tier: db # has to match .spec.template.metadata.labels
  serviceName: "postgres"
  replicas: 2 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        tier: db # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 3306
          name: db
        volumeMounts:
        - name: gp3-pvc
          mountPath: /var/lib/postgresql/data
        env:
        - name: POSTGRES_DB 
          value: "postgres_db"
        - name: POSTGRES_USER
          value: "postgres_user"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_PASSWORD
  volumeClaimTemplates:
  metadata:
  name: gp3-pvc
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
    storageClassName: gp3