apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  labels:
    tier: db
spec:
  ports:
  - port: 5432
    name: db
  clusterIP: None
  selector:
    tier: db

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      tier: db
  serviceName: "postgres-headless"
  replicas: 1 
  minReadySeconds: 10 
  template:
    metadata:
      labels:
        tier: db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
          name: db
        volumeMounts:
        - name: gp3-pvc
          mountPath: /var/lib/postgresql/data
        env:
        - name: POSTGRES_DB 
          value: "postgres_db"
        - name: POSTGRES_USER
          value: "postgres_user"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_PASSWORD
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
  volumeClaimTemplates:
  - metadata:
      name: gp3-pvc
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
      storageClassName: gp3