apiVersion: v1
data:
  POSTGRES_PASSWORD: cG9zdGdyZXNfcGFzc3dvcmQ=
kind: Secret
metadata:
  creationTimestamp: "2026-09-27T08:09:52Z"
  name: postgres-secrets
  namespace: default
  resourceVersion: "9666"
  uid: ff3851e3-2374-49c4-9141-65e954460afd
type: Opaque